version: "3.8"

services:

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus-data:/etc/prometheus       #past metrics info stored in named volume
    configs:
      - source: prometheus-config            # From host to container 
        target: /etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring-net
    deploy:
      placement:
        constraints:
          - node.role == manager

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - monitoring-net
    volumes:
      - grafana-data:/var/lib/grafana
    deploy:
      placement:
        constraints:
          - node.role == manager

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    deploy:
      mode: global             # Runs on EVERY node
    ports:
      - "8082:8080"
    networks:
      - monitoring-net
    volumes:
      - /:/rootfs:ro                     # Gives access to host filesystem
      - /var/run:/var/run:ro             # Access to system runtime info
      - /sys:/sys:ro                     # Access to Kernel/system metrics
      - /var/lib/docker/:/var/lib/docker:ro         # Access to Docker container data

networks:
  monitoring-net:
    driver: overlay

volumes:
  prometheus-data:
  grafana-data:

configs:
  prometheus-config:
    file: ./prometheus.yml